const state={theme:'Midnight',brand:'My Website',title:'Build your website.',text:'Create a beautiful mobile website in minutes.',button:'Get Started'};
const themes={Midnight:{bg:'linear-gradient(145deg,#111827,#4f46e5)',fg:'#fff'},Ocean:{bg:'linear-gradient(145deg,#075985,#06b6d4)',fg:'#fff'},Sunset:{bg:'linear-gradient(145deg,#9a3412,#f97316)',fg:'#fff'},Clean:{bg:'linear-gradient(145deg,#f8fafc,#e2e8f0)',fg:'#111'}};
const blocks=[['hero','🚀','Hero'],['text','T','Text'],['image','🖼️','Image'],['button','🔘','Button'],['features','▦','Features'],['contact','☎️','Contact']];
const panels={
 theme:{title:'Theme',html:`<div class="option-grid">${Object.keys(themes).map(x=>`<button class="option ${x==='Midnight'?'selected':''}" data-theme="${x}"><strong>${x}</strong><small>Premium style</small></button>`).join('')}</div>`},
 content:{title:'Content',html:`<div class="field"><label>Website name</label><input id="brandInput" value="${state.brand}"></div><div class="field"><label>Headline</label><input id="titleInput" value="${state.title}"></div><div class="field"><label>Description</label><textarea id="textInput" rows="3">${state.text}</textarea></div><div class="field"><label>Button text</label><input id="buttonInput" value="${state.button}"></div><button class="save" id="saveContent">Update live preview</button>`},
 sections:{title:'Add & Arrange',html:`<p class="panel-help">Drag a block into the live preview, or tap it to add.</p><div class="block-grid">${blocks.map(([id,icon,name])=>`<button class="block-card" draggable="true" data-block="${id}"><span>${icon}</span><b>${name}</b><small>Drag to preview</small></button>`).join('')}</div><div class="drop-hint" id="dropHint">↕ Drop here to add a section</div>`},
 style:{title:'Design',html:`<div class="field"><label>Preview device</label><select id="device"><option>Mobile</option><option>Tablet</option><option>Desktop</option></select></div><div class="field"><label>Corner radius</label><input type="range" min="8" max="36" value="24" id="radius"></div>`},
 settings:{title:'Settings',html:`<div class="section-row"><span>Auto-save</span><b>ON</b></div><div class="section-row"><span>Mobile friendly</span><b>ON</b></div><div class="section-row"><span>Publish status</span><b>Draft</b></div>`}
};
const panel=document.getElementById('editorPanel'),back=document.getElementById('backdrop'),body=document.getElementById('panelBody'),pt=document.getElementById('panelTitle'),site=document.getElementById('sitePreview');
function openPanel(name){const p=panels[name];pt.textContent=p.title;body.innerHTML=p.html;panel.classList.add('open');back.classList.add('open');panel.setAttribute('aria-hidden','false');bindPanel(name)}
function closePanel(){panel.classList.remove('open');back.classList.remove('open');panel.setAttribute('aria-hidden','true')}
function bindPanel(name){
 document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;const t=themes[state.theme];document.getElementById('heroPreview').style.background=t.bg;document.getElementById('heroPreview').style.color=t.fg;document.querySelectorAll('[data-theme]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');toast('Theme applied')});
 const save=document.getElementById('saveContent');if(save)save.onclick=()=>{state.brand=document.getElementById('brandInput').value||'My Website';state.title=document.getElementById('titleInput').value||'Build your website.';state.text=document.getElementById('textInput').value||'';state.button=document.getElementById('buttonInput').value||'Get Started';document.getElementById('previewBrand').textContent=state.brand;document.getElementById('previewTitle').textContent=state.title;document.getElementById('previewText').textContent=state.text;document.getElementById('previewButton').textContent=state.button;toast('Live preview updated')};
 const r=document.getElementById('radius');if(r)r.oninput=e=>document.getElementById('heroPreview').style.borderRadius=e.target.value+'px';
 document.querySelectorAll('[data-block]').forEach(el=>{el.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',el.dataset.block);site.classList.add('drag-ready')});el.addEventListener('dragend',()=>site.classList.remove('drag-ready'));el.addEventListener('click',()=>addBlock(el.dataset.block))});
}
function addBlock(type){const labels={hero:'Hero section',text:'Text section',image:'Image section',button:'Button section',features:'Features section',contact:'Contact section'};const box=document.createElement('div');box.className='added-block';box.draggable=true;box.dataset.added='true';box.innerHTML=`<span>${labels[type]}</span><button aria-label="Remove section">×</button>`;box.querySelector('button').onclick=()=>box.remove();box.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain','move:'+Math.random());window.draggedBlock=box});box.addEventListener('dragover',e=>e.preventDefault());box.addEventListener('drop',e=>{e.preventDefault();if(window.draggedBlock&&window.draggedBlock!==box)box.parentNode.insertBefore(window.draggedBlock,box)});site.appendChild(box);toast(`${labels[type]} added`)}
site.addEventListener('dragover',e=>{e.preventDefault();site.classList.add('drop-active')});site.addEventListener('dragleave',e=>{if(!site.contains(e.relatedTarget))site.classList.remove('drop-active')});site.addEventListener('drop',e=>{e.preventDefault();site.classList.remove('drop-active');const type=e.dataTransfer.getData('text/plain');if(type&&!type.startsWith('move:'))addBlock(type);else if(window.draggedBlock){site.appendChild(window.draggedBlock);toast('Section moved')}});
document.querySelectorAll('.tool').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));t.classList.add('active');openPanel(t.dataset.panel)});
document.getElementById('closePanel').onclick=closePanel;back.onclick=closePanel;
document.getElementById('previewButton').onclick=()=>{openPanel('content');setTimeout(()=>document.getElementById('titleInput')?.focus(),100);toast('Edit your website')};
document.getElementById('publishBtn').onclick=()=>toast('Website saved — publish connection ready');
function toast(msg){const x=document.getElementById('toast');x.textContent=msg;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
